unique_ids:
  assets:
    theme.css: C26SOLFAIAAUZWN6SGCUPGHZFNR23VMG
  forms:
    Form1: WKKJZVJ7X7YT34GTF5Z2VWE2J32LBZAM
    Layouts.BaseLayout: BBMMXMPLBE5O5A75ZWMHDBCQHEUWRZBU
  modules:
    Layouts: X5N7ZWWFM3PEN2AHUWLGW7P7MSQ6XM7U
  scripts: {}
  server_modules: {}
